language: php

sudo: false

dist: trusty

git:
  depth: 5

php:
  - 5.6

before_install:
    # determine INI file
    - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then export INI=/etc/hhvm/php.ini; else export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
     # disable xdebug if available
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    # disable default memory limit
    - echo memory_limit = -1 >> $INI

install:
    # install dependencies using system provided composer binary
    - composer install

script:
    # run test suite directories in parallel using GNU parallel
    - ./vendor/bin/phpunit ./tests/;

    - ./vendor/bin/phploc ./src/;

    - ./vendor/bin/pdepend --summary-xml=/tmp/dpend.xml ./src/;

    - ./vendor/bin/phpcpd ./src/;

    - ./vendor/bin/phpmd ./src/ xml rulesets/codesize.xml;

    # Pour ignorer les errors et warnings
    # - ./vendor/bin/phpcs --severity=0 ./app/;
    - ./vendor/bin/phpcs -n ./src/;

    - ./update.sh
